// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.motorcontrol.MotorController;
import edu.wpi.first.wpilibj.motorcontrol.PWMSparkMax;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class DriveTrain extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private PWMSparkMax canSpark_DriveLeft_2;
private PWMSparkMax canSpark_DriveLeft_1;
private PWMSparkMax canSPark_DriveRight_1;
private PWMSparkMax canSPark_DriveRight_2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    public DriveTrain() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
canSpark_DriveLeft_2 = new PWMSparkMax(1);
 addChild("CanSpark_DriveLeft_2",canSpark_DriveLeft_2);
 canSpark_DriveLeft_2.setInverted(false);

canSpark_DriveLeft_1 = new PWMSparkMax(0);
 addChild("CanSpark_DriveLeft_1",canSpark_DriveLeft_1);
 canSpark_DriveLeft_1.setInverted(false);

canSPark_DriveRight_1 = new PWMSparkMax(2);
 addChild("CanSPark_DriveRight_1",canSPark_DriveRight_1);
 canSPark_DriveRight_1.setInverted(false);

canSPark_DriveRight_2 = new PWMSparkMax(3);
 addChild("CanSPark_DriveRight_2",canSPark_DriveRight_2);
 canSPark_DriveRight_2.setInverted(false);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

