package frc.robot.commands;

import java.lang.module.ModuleDescriptor.Requires;

import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.Robot;
import frc.robot.RobotContainer;
import frc.robot.subsystems.SubDriveTrain;
public class CmdAutoDriveStraght extends CommandBase {

    private final double targetPosinch = 36;
    private final double speed = .15;
    private final double Heading = 0;
    private final double distance = 0;
    private boolean bDone = false;
    public CmdAutoDriveStraght() {




        //  addRequirements(RobotContainer.getInstance().subDriveTrain);
      // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
          // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
  
          // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
          // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
  
          // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
      }
          
  
      
  
      // Called when the command is initially scheduled.
      @Override
      public void initialize() {

        RobotContainer.getInstance().subDriveTrain.resetBothEncoders();
        RobotContainer.getInstance().subDriveTrain.Drive(speed, speed);

      }
  
      // Called every time the scheduler runs while the command is scheduled.
      @Override
      public void execute() {
  
          System.err.println("Drive " + RobotContainer.getInstance().subDriveTrain.getEncoderPosLeft_Inches() + " of " + targetPosinch );
          
if(RobotContainer.getInstance().subDriveTrain.getEncoderPosLeft_Inches() >= targetPosinch){
bDone = true;
end(false);

}

      }
  
      // Called once the command ends or is interrupted.
      @Override
      public void end(boolean interrupted) {
        RobotContainer.getInstance().subDriveTrain.Drive(0, 0);

      }
  
      // Returns true when the command should end.
      @Override
      public boolean isFinished() {
          return bDone;
      }
  
      @Override
      public boolean runsWhenDisabled() {
          // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
          return false;
  
          // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
      }
 
      private void autoDrive(){




      }
    
}
