// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;

import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.Robot;
import frc.robot.RobotContainer;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.SubLauncher;
import frc.robot.RobotMath;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class CmdIndexerLaunch extends CommandBase {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    // private SubLauncher subLauncher;

    public boolean bdone = false;
    private double RunningTime;
    private double IdleTime;
    private double TargetTime;
    private double RestartTime;

    private double DelayTime = 0.1; // sec
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    // ************** uncomment for full robot*********** */
    public CmdIndexerLaunch() {
        // flyWeelSpeedRPM = RPM;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDERz ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        // ********************* uncomment for full robot */
        // subLauncher = RobotContainer.getInstance().subLauncher;
        // addRequirements(subLauncher);
        // ****************** see above************* */

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        // bdone = false;
        if (RobotContainer.bLogging) {
            System.err.println("IndexerLaunch");
        }

        RunningTime = RobotMath.getTime();
        IdleTime = RunningTime + (DelayTime);
        TargetTime = IdleTime + (8 * DelayTime);
        RestartTime = TargetTime + (5 * DelayTime);

        addRequirements(RobotContainer.getInstance().subIndexer);
        RobotContainer.getInstance().subIndexer.FeederStop();
        bdone = false;
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        // System.err.println(String.format("launcherExecute
        // flyWeelSpeedRPMz:%1$.3d",flyWeelSpeedRPM));
        if (RobotContainer.bLogging) {
            System.err.println("IncdexerLaunch - Execute");
        }
        
        double CurrentTime = RobotMath.getTime();
        if (CurrentTime >= IdleTime && CurrentTime < TargetTime) {
            RobotContainer.getInstance().subIndexer.Launchtrack();
            RobotContainer.getInstance().subIndexer.FeederLaunch();

        } else if (CurrentTime >= TargetTime && CurrentTime < RestartTime) {
            RobotContainer.getInstance().subIndexer.FeederStop();
        } else if (CurrentTime >= RestartTime) {
            RobotContainer.getInstance().subIndexer.starttrack();
            bdone = true;
        }

    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        RobotContainer.getInstance().subIndexer.FeederHolding();
        bdone = true;
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return bdone;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
