package frc.robot.commands;

import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.SubLimelight;

public class CmdLimeLightPipeline extends CommandBase {
  
  private final SubLimelight subLimeLight;
  public CmdLimeLightPipeline(SubLimelight subsystem) {
    // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    subLimeLight = subsystem;
    addRequirements(subLimeLight);
  }

  // Called just before this Command runs the first time
  @Override
  public void initialize() {
    subLimeLight.setPipeline(0);
  }

  // Called repeatedly when this Command is scheduled to run
  @Override
  public void execute() {
    subLimeLight.setPipeline(1);
  }

  // Make this return true when this Command no longer needs to run execute()
  @Override
  public boolean isFinished() {
    return false;
  }

  // Called once the command ends or is interrupted.
  @Override
  public void end(boolean interrupted) {
      subLimeLight.setPipeline(0);
  }

  @Override
  public boolean runsWhenDisabled() {
      // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
      return false;

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
  }
}
