


package frc.robot.commands;

import frc.robot.*;
import edu.wpi.first.wpilibj2.command.CommandBase;
//import edu.wpi.first.wpilibj2.buttons.JoystickButton;
import edu.wpi.first.wpilibj.Joystick;
import frc.robot.subsystems.SubDriveTrain;
import frc.robot.subsystems.SubGyro;


/**
 *
 */
public class CmdTeleDrive extends CommandBase {

    private final SubDriveTrain subDriveTrain;
    private final SubGyro subGyro;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public CmdTeleDrive(SubDriveTrain newDriveTrain, SubGyro newGyro) {


		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
			// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
	
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
			// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	
			subGyro = newGyro;
			addRequirements(subGyro);
			
			subDriveTrain = newDriveTrain;
			addRequirements(subDriveTrain);
	
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		}

    // Called just before this Command runs the first time
    @Override
    public void initialize() {
        Robot.subDriveTrain.resetEncoder_LeftDrive();
        Robot.subDriveTrain.resetEncoder_RightDrive();
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    public void execute() {
        Robot.subDriveTrain.Drive(Robot.oi.joyDrive());
        

    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    public boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    public void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    public void interrupted() {
		end();
	}
}
