package frc.robot.commands;

import java.lang.module.ModuleDescriptor.Requires;

import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.Robot;
import frc.robot.RobotContainer;
import frc.robot.Constants.limelightConstants.cameras;
import frc.robot.subsystems.SubLimelight;
import frc.robot.Constants;

public class LChCamPipline extends CommandBase {

private String ipcam1 = "http://10.36.68.12:5801";
private String ipcam2 = "http://10.36.68.11:5801";
private boolean activeCam;

private cameras cCam ;
private int pipe;
private SubLimelight.CAM_MODE CMode;

    public LChCamPipline(cameras cam, int pipline, SubLimelight.CAM_MODE mode) {

        cCam = cam;
        pipe = pipline;
        CMode = mode;
        // addRequirements(RobotContainer.getInstance().subDriveTrain);

    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        System.err.println("CmdToggleCamara");
        
        //update specified cam with 
        if(cCam == cameras.limelight_high){
            RobotContainer.getInstance().subLimelightHigh.setPipeline(pipe);
            RobotContainer.getInstance().subLimelightHigh.setCamMode(CMode);
        }
        else if (cCam == cameras.limelight_low){
            RobotContainer.getInstance().subLimelightLow.setPipeline(pipe);
            RobotContainer.getInstance().subLimelightLow.setCamMode(CMode);
        }
        
        //update to specificed pipline

        //update cammode as specfied


    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {

        

    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return true;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }

}
